CREATE TABLE `AWS-S3`.`USER` (
  `USER_PROFILE_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `USERNAME` VARCHAR(45) NULL,
  `USER_PROFILE_IMAGE_LINK` VARCHAR(100) NULL DEFAULT 'aws s3 key',
  PRIMARY KEY (`USER_PROFILE_ID`));

